from __future__ import annotations

OPENSHIFT_CLUSTER_RESOURCES = [
    ("config.openshift.io", "v1", "clusterversions", "ClusterVersion"),
    ("config.openshift.io", "v1", "clusteroperators", "ClusterOperator"),
    ("config.openshift.io", "v1", "infrastructures", "Infrastructure"),
    ("config.openshift.io", "v1", "proxies", "Proxy"),
    ("config.openshift.io", "v1", "networks", "Network"),
    ("config.openshift.io", "v1", "dnses", "DNS"),
    ("config.openshift.io", "v1", "authentications", "Authentication"),
    ("config.openshift.io", "v1", "images", "Image"),
    ("config.openshift.io", "v1", "apiservers", "APIServer"),
    ("config.openshift.io", "v1", "schedulers", "Scheduler"),
    ("config.openshift.io", "v1", "oauths", "OAuth"),
    ("machineconfiguration.openshift.io", "v1", "machineconfigpools", "MachineConfigPool"),
    ("route.openshift.io", "v1", "routes", "Route"),
    ("operator.openshift.io", "v1", "ingresscontrollers", "IngressController"),
    ("operator.openshift.io", "v1", "kubeapiservers", "KubeAPIServer"),
    ("operator.openshift.io", "v1", "kubecontrollermanagers", "KubeControllerManager"),
    ("operator.openshift.io", "v1", "kubeschedulers", "KubeScheduler"),
    ("operator.openshift.io", "v1", "etcds", "Etcd"),
    ("security.openshift.io", "v1", "securitycontextconstraints", "SecurityContextConstraints"),
    ("operators.coreos.com", "v1alpha1", "clusterserviceversions", "ClusterServiceVersion"),
    ("operators.coreos.com", "v1alpha1", "subscriptions", "Subscription"),
    ("operators.coreos.com", "v1alpha1", "installplans", "InstallPlan"),
    ("operators.coreos.com", "v1alpha1", "catalogsources", "CatalogSource"),
    ("operators.coreos.com", "v1", "operatorgroups", "OperatorGroup"),
    ("machine.openshift.io", "v1beta1", "machines", "Machine"),
    ("machine.openshift.io", "v1beta1", "machinesets", "MachineSet"),
    ("machine.openshift.io", "v1beta1", "machinehealthchecks", "MachineHealthCheck"),
]
