apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ocp-audit-agent
  namespace: ocp-audit
spec:
  podSelector:
    matchLabels: {app: ocp-audit-agent, component: server}
  policyTypes: ["Ingress","Egress"]
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: openshift-ingress
    ports:
    - protocol: TCP
      port: 8080
  egress:
  - to:
    - podSelector:
        matchLabels: {app: ocp-audit-agent, component: postgres}
    ports:
    - protocol: TCP
      port: 5432
  - to:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 443
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
    ports:
    - protocol: TCP
      port: 443
  # Adjust ingress for corporate ingress namespaces or direct port-forward access.
